### ISSUE TITLE
Improve workflow

### ISSUE THREAD

**Issue by BeiyanYunyi** [one-among-us/data#102]
当前似乎没有办法做到“一边编辑一边预览效果”（`yarn build-preview` 未按预期工作），这对不熟悉 Markdown 的人来说会很糟糕。我即使长期使用 Markdown，在提交前也要反复确认效果是否正确。并且，当前似乎已经有页面出现了这种“渲染不符合预期”的情况：

![图片](https://user-images.githubusercontent.com/14120445/221574602-43b8fe5d-5304-43ad-b613-fbd6ec2da15a.png)

像这里（13-14 行），像是忘了加空格换行，如果继续保持当前工作流，这样的事情只会反复发生。

**Comment by hykilpikonna** [comment]
曾经是有 PR preview 和本地预览功能的（见 #63 ），这个功能之前的实现是从 gh-pages 分支下载 web 的部署结果再把 data url 改成本地，但是 web 部署位置改到 cloudflare pages 之后这个功能一直没有更新
