### ISSUE TITLE
扶她菊花茶

### ISSUE THREAD

**Issue by KristallWang** [one-among-us/data#111]
https://www.zhihu.com/people/bu-shi-zi-de-wen-hao

**Comment by LiAlH4-Tr** [comment]
或许有更多的信息吗

**Comment by kosakuraiori** [comment]
梦回五年前（苦笑）

**Comment by Twinsherry** [comment]
联系了与她有关的艾瑞卡，但是目前没有收到回复。
根据相关内容确认与雪舞梨花梦有关，但梨花已经逝世。
请问有具体的情况吗？

**Comment by Twinsherry** [comment]
To-do: 需要一段时间的查证

**Comment by Twinsherry** [comment]
> 内容其实相对足够编撰一个简单的条目了，但缺乏逝世日期，可能还是需要基本的查证。

认定日期：2018-07-11（or 07-10）
