### ISSUE TITLE
猎鹰…

### ISSUE THREAD

**Issue by KristallWang** [one-among-us/data#112]
车祸…
https://twitter.com/Beyond93Forever/status/1644206906192568321

https://space.bilibili.com/361223410
https://space.bilibili.com/2512475

**Comment by KristallWang** [comment]
https://twitter.com/TaroLeohearts/status/1644275608774639616

https://leohearts.com/archives/farewell-yingying.html

https://twitter.com/TaroLeohearts/status/1644265810570117120

**Comment by BUAA-Wjay** [comment]
我已提交了相关页面的PR，希望有人能进一步完善
