### ISSUE TITLE
有没有办法用零知识证明的方法证明逝者的具体数目

### ISSUE THREAD

**Issue by moe-rika** [one-among-us/data#116]
> From January 1, 2023 to the March 25th, 2023, there are at least 91 transgenders lost their lives, averaging out to one person every day. There are already transgender individuals that are forced to be refugee[21]. My knowledge is limited to those who had a Twitter account or were active on QQ. On Twitter, there have been 42 confirmed deaths among transgender individuals, and in my other social circles, mainly on QQ, there have been 49 confirmed deaths. This is an unprecedented and devastating loss of life, and it is heartbreaking to think about the countless others who have suffered and passed away beyond the scope of my knowledge. These individuals were someone’s friends, family members, and loved ones, and their loss is a profound tragedy that must not be ignored.

> From January 1, 2023 to the February 11th, 2023, there are at least 58 transgenders lost their lives(update on 2023-02-17, there are 3 more transgender lost their lives), averaging out to one person every day. There is already transgender that is forced to be a refugee[17]. My knowledge is limited to those who had a Twitter account or were active on QQ. On Twitter, there have been 21 confirmed deaths among transgender individuals, and in my other social circles, mainly on QQ, there have been 37 confirmed deaths. This is an unprecedented and devastating loss of life, and it is heartbreaking to think about the countless others who have suffered and passed away beyond the scope of my knowledge. These individuals were someone’s friends, family members, and loved ones, and their loss is a profound tragedy that must not be ignored.
> 
> The situation for transgender individuals in China is dire, with ongoing erasure of lives and increasing deaths happening right now. The government’s persecution and discrimination against transgender is unacceptable and must be addressed immediately.
> 
> As a member of the transgender community, I am all too familiar with the dire situation, which highlights the urgent need for help and protection. Every day, Chinese transgenders, including myself, are facing threats and losing lives. It is imperative that the international community takes action and offers support in our fight for survival. The loss of so many lives is a tragedy that cannot be ignored, and it is imperative that action is taken to support us from this ongoing persecution.
> 
> All we ask for is a chance to live.
> 
> Chunqing “Jyn” Shan
> 
> 2023-02-11
> 
> Updated on 2023-02-17
> UPDATES:
> 
> 2023-02-17: 3 more confirmed deaths, the total number of confirmed deaths is 61.

one-among-us的统计不全，或者琴春夸大了。
有没有办法向琴春要名单，并且在不公布名单的情况下证明其存在。

**Comment by sauricat** [comment]
抱歉，我们项目和琴春没有直接联系。如果你有意向的话，可以帮忙问一问，以「希望完善那些秋叶网站」的名义也可以，毕竟这个网站的内容是大家共同贡献的。

One Among Us 目前没有涉及直接统计逝者数量的工作，这是一个非常难的社会统计学问题。我们只负责收录我们所知并且允许被纪念的逝者。
