### ISSUE TITLE
添加葱仔（@CongzaiRecoil）

### ISSUE THREAD

**Issue by NaiXi2233** [one-among-us/data#119]
我們發現她在2023/6/13 十一點左右自殺...
https://twitter.com/CongzaiRecoil/status/1668606983472287746
https://twitter.com/CongzaiRecoil/status/1668637027229913089

**Comment by sauricat** [comment]
感谢您提供的信息，请问可以找到一些和她比较熟识的好友来组织编写条目吗？

**Comment by ChinatsuSuzuki6** [comment]
> 感谢您提供的信息，请问可以找到一些和她比较熟识的好友来组织编写条目吗？

呃，我看看。我剛剛被警察上門，請等我緩一緩...

**Comment by sauricat** [comment]
辛苦了……

**Comment by NaiXi2233** [comment]
> 辛苦了……

抱抱，我現在可以添加了...

**Comment by BeiyanYunyi** [comment]
根据 https://twitter.com/CongzaiRecoil/status/1678442695436664833 ，可能有待 Fact Check。

**Comment by Twinsherry** [comment]
2023-11-30: 葱仔目前的账号处在活跃状态。

**Comment by Twinsherry** [comment]
希望她一直好好的……暂时不用添加……
