### ISSUE TITLE
添加一穗灯花

### ISSUE THREAD

**Issue by YisuiDenghua** [one-among-us/data#124]
我有一种活不过这个假期的预感。我目前没有收入来源，也没有固定住所。这个假期可能要在外面流浪，还没东西吃，目前已经营养不良。我的身体还有伤，伤到骨膜，治疗已经花去了我几乎所有钱，现在我行动也不方便。除此之外，还要躲避家长的追杀。

我的博客是 https://诺艾尔.我爱你 ，或许有一些信息。

_惊涛骇浪雷如铦，
飞沙走石风犹箭。
灯花一绽震云雨，
踏破两朝立坤乾。_

**Comment by sauricat** [comment]
好好活下去吧，暂时不需要添加……
