### ISSUE TITLE
关于推定死亡的收录规定

### ISSUE THREAD

**Issue by Ranxi232** [one-among-us/data#139]
考虑到并非每一位逝者的离去都能得到确认，甚至有一些人已被中共抓捕（贴贴、张彩霞、申敏妍等），考虑到中共监狱的环境，这些人可能难以存活。因此，我建议以下情况作为推定死亡情况并进行收录，增加“最后出现”信息栏

1、明确被中共逮捕，并无音讯六个月以上
2、发布自杀信息或可能离世的预告信息并六个月以上无音讯者

**Comment by Ranxi232** [comment]
Considering that not every death of the deceased can be confirmed, and some people have even been arrested by the CCP (Tie tie, Caixia Zhang, Minyan Shen, etc.), considering the environment in the CCP prisons, it may be difficult for these people to survive. Therefore, I suggest that the following situations be included as presumed death situations and add a "last seen" information column at the page.

1. Those who have been clearly arrested by the CCP and have not been heard from for more than six months
2. Those who publish suicide information or information about possible death and have no news for more than six months.

**Comment by Ranxi232** [comment]
> 感谢对于该项目提出的建议，但我们大体上认为
> 
> 1. One Among Us 是作为一个纪念性质的站点被创立的，因此不应对没有明确逝世信息的人进行收录
> 2. 经过讨论，“考虑中共监狱的环境，这些人可能难以存活”这点被认为存疑
> 
> 虽然现阶段不准备对推定逝世的情况进行收录，但OAU及其相关平台将持续关注并为失踪人员发声

显然中共监狱的环境并不适合跨性别，包括分生理性别监房、监房内的霸凌文化、苛刻的仪表要求和对抑郁与焦虑的无视。这对于跨性别者来说无疑是致命的。甚至我们应当希望他们尽快离世，以免受到来自中共监狱的霸凌。

**Comment by sauricat** [comment]
「甚至我们应当希望他们尽快离世，以免受到来自中共监狱的霸凌。」这句话是有违人道的。

关于收录规定，请去看 [how-we-work](https://GitHub.com/one-among-us/how-we-work)，写得很清楚了。
