### ISSUE TITLE
Add 喵小泪

### ISSUE THREAD

**Issue by sauricat** [one-among-us/data#163]
https://twitter.com/LianCirilla/status/1736309527493202260

![IMG_20231217_225636_641](https://github.com/one-among-us/data/assets/3533655/dbed6e14-7cce-48a2-85b8-33c2bfbbd393)

https://twitter.com/ibuki_nanazuki/status/1736549854640521396

![20231217_225341](https://github.com/one-among-us/data/assets/3533655/6f0aa981-0f54-47c6-89ba-6452ff094624)
![20231217_225342](https://github.com/one-among-us/data/assets/3533655/fa5f88d2-a5e9-4952-94ed-6bfccf864a3b)

**Comment by Twinsherry** [comment]
安安还在恢复精神，应该还需要等一段时间，可能她会自己写一些内容。
