### ISSUE TITLE
Add 星璃璃

### ISSUE THREAD

**Issue by P-ZH** [one-among-us/data#167]
<img width="596" alt="截屏2024-01-02 00 50 31" src="https://github.com/one-among-us/data/assets/16199974/a65e1b1e-ff1f-443a-b0dd-6a42ec5db9dd">

**Comment by LiAlH4-Tr** [comment]
> <img width="596" alt="截屏2024-01-02 00 50 31" src="https://github.com/one-among-us/data/assets/16199974/a65e1b1e-ff1f-443a-b0dd-6a42ec5db9dd">
> 

請立即刪除相關內容，謝謝，否則你們可能會面臨麻煩

**Comment by Twinsherry** [comment]
Not planned yet
