### ISSUE TITLE
Hsiu Suwako

### ISSUE THREAD

**Issue by huaji749** [one-among-us/data#187]
https://twitter.com/Hsiu_suwako/status/1746158275345932624
PS：本人是TA的初中同学 在TA去世之后才知道了TA作为跨性别的事情 如果需要更多信息我也可以帮忙核实

**Comment by Twinsherry** [comment]
感谢您……可以查看我们的一些条目作为模板来提供profile信息。
如果有相关的ta的梦想，故事，愿望之类的也可以一并在此issue写下或发送到我们的info邮箱，谢谢您。

**Comment by Twinsherry** [comment]
您好，諏訪子近日刚刚从医院出院，目前情况尚可。
谢谢您的关心……祝大家新春都能幸福快乐。
issue我先关闭了。
