### ISSUE TITLE
Add shi_Yumiaoya (鱼喵)

### ISSUE THREAD

**Issue by LS-KR** [one-among-us/data#193]
https://twitter.com/Fthx14/status/1759245202001399963
https://twitter.com/XUEQIUxka/status/1759250373427253277
https://twitter.com/XUEQIUxka/status/1759255778542887263

may help:
https://twitter.com/XUEQIUxka/status/1759257317529485336

**Comment by AnnaBeiyan** [comment]
此人真实死亡日期应为2024年3月2日。建议reopen此issue并作适当修改。https://x.com/xueqiuxka/status/1784960940162887989

**Comment by Twinsherry** [comment]
> 此人真实死亡日期应为2024年3月2日。建议reopen此issue并作适当修改。https://x.com/xueqiuxka/status/1784960940162887989

您好，感谢您对相关事件和社群伙伴们的关注。

One Among Us 的成员已经关注到此事，由于事件牵涉众多，部分朋友精神状态不稳定等问题，我们会在事情完全明晰和相关社群朋友情况稳定后对条目进行进一步的修订。
