### ISSUE TITLE
Add 玖月折耳猫

### ISSUE THREAD

**Issue by sauricat** [one-among-us/data#202]
[寒涟漪的悼文](https://t.me/Lianyi520/565)

> 忽然想到了折耳猫。这个从2021年开始就向我求助的疑似bpd的小孩。前后搞崩了四个帮助她的人，自杀的次数可能都有几十次了。
>
> 送她进过精神科住院，也找过人收留过她很长一段时间，给过她很多钱，更找过好几个人陪伴她，无论是线下陪伴，还是线上聊天。最终，她的各种疑似bpd行为，成功搞崩了几乎所有帮助她的人的精神状态。
>
> 她最终还是去世了，这个结果也不意外。
>
> 每次自杀之前，她都会向身边所有人发布通告，还有她的所在地址，姓名，电话。她也时常会向其他人发家里人的电话。让其他人在她自杀的时候能够帮她报警。
>
> 这次她玩脱了，自杀的次数太多，终于一个及时帮她报警的人也没有了。她自己也知道终会有这么一天，所以每一次自杀都是抱着想法：“自杀如果没死，就继续活，如果自杀死了，那死掉也好。”
>
> 最终她最后一次自杀的导火索，却又是那“为什么没有人给我一千块钱”。
>
> 她缺爱，她自己知道她缺爱，大家也知道她缺爱。她自己知道她自杀是为了得到更多关注，更多爱，大家也都知道她自杀是为了得到更多关注，更多爱。
>
> 但是她的疑似bpd，却又能把绝大部分陪伴她的人精神状态搞崩。
>
> 一年，两年，三年。
>
> 所有人都知道这是一个“狼来了”的故事，她自己也知道这是一个“狼来了”的故事。
>
> 最终，狼真的来了，所有人也知道狼会有真的来的一天。
>
> 但是大家的耐心，都已经被消磨殆尽了。
>
> 她的问题说实话，也远远没有到达多严重的地步，一直有人给她提供情绪价值，一直有人给她提供钱，一直有人给她提供住处，一直有人给她及时报警。一直能有人帮她处理校园霸凌问题，一直有人能帮她处理家庭矛盾。
>
> 一年，两年，三年。
>
> 她也能活一年算一年。
>
> 但是，其他人呢？资源是有限的。并没有亿万富翁愿意每个月都持续给我们捐大额的钱。
>
> 折耳猫，她如果生在发达国家，又或者是生在梨子梨那样的富二代家庭，我相信她能活的很好，会有足够的资源，钱和爱来弥补她天生的疑似bpd的缺憾。
>
> 但如今，终究只能化作一声长叹。

carb 说:
> 没准这也是她们的一种策略
>
> 把所有人都耗到没力气 自己就可以放心走了

**Comment by Twinsherry** [comment]
地区：陕西西安
离世：2024-02-26

**Comment by Yuki-Luofan** [comment]
## 你好，這裏是洛坊，我想這需要更多信息補充，目前尚不能排除“轉生林檎”的情況，下面是對於懷疑“轉生林檎”的推斷和猜測，隨便爆點料。

首先在繼續之前明確我在講述時的身份——ta認爲的“鈴木真依”

在我作爲“鈴木真依”時“2022/12/~”,ta曾經因爲自殺干預的原因找到我（CatEars project 的原型），在同時還有另外一位找到我，就是“ARTS”。

我在那時和我的朋友一起陪ta聊天，希望ta可以因爲陪伴不要自殺，並在這個過程中ta提出了要和“我”作爲情人關係生活，我就借此給ta提了“不可以自殺”的條件並獲得同意（在這時我同時進行了對於“ARTS”的開導並獲得了她真遺書的加密版本，我使用工具跑了字典，失敗了，後來該副本因爲特殊原因被丟棄），並在這之後進行了大約半年的“文游式”戀愛（即所有信息皆提供虛假的，使用了病弱人設以加强控制之類的...其目標在於保護自己和牽制ta避免自殺行爲），在這之間ta提到了自己曾經進行假紫砂...騙取關注和金幣的行爲並提議在人設崩塌圈不到后使用“轉生林檎”繼續，我接下話題並提供了避免用戶畫像聯想的方法...在後來局勢變化導致我壓力山大（ta會假紫砂並使用紫砂威脅我爆金幣），我將我的人物“鈴木真依”使用充滿破綻的方式寫死了。（那時我就已經在標榜自己為情強，所以是在調查了大量關於心臟病和醫療護理的資料后進行的，因爲一些原因，我希望和我一樣的情強可以很快看出，故使用奇妙深刻而不算離譜的死亡方式——呼吸肌麻痹合并肺炎，因爲臥床和虛弱引起xxx云云）。

## 我寫上面的廢話可以在這個主題概括為：
* 我不是真的想和ta戀愛。
* 我在和ta戀愛時因爲安全考慮提供虛假身份，這是我的罪過
* 我在和ta戀愛期間進行了類似於ARG的小範圍表演來鞏固人設以加强控制
* ta會假紫砂並使用紫砂威脅我爆金幣，并且炫耀自己曾經得手
* ta會在人設崩塌后嘗試轉生林檎
* 我在去年的4月份徹底寫死鈴木真依，因爲我無法承受基於生命的綁架
* 我是騙子
## 隨便的題外話：
* 我在和arts聊天時獲得了好多照片，很好看
* arts知道我帶著面具，並表示在以後會幫助我圓謊和自炒（和黑塔一起討論我的面具並放出結論），但我需要把檸檬光打趴下（ddos）並將對於檸檬光的黑屁鑄造成NFT
* arts會在消失后一周定時傳送密碼，届時就可以解密壓縮包獲得真遺書（因爲tg因爲寫死被丟棄，遺書本體存在的電腦因爲警察對我涉及毒品案的調查被沒收）
* arts...嗯，曾經被認妹妹了嗚嗚嗚

**Comment by Twinsherry** [comment]
> ## 你好，這裏是洛坊，我想這需要更多信息補充，目前尚不能排除“轉生林檎”的情況，下面是對於懷疑“轉生林檎”的一些參考，隨便爆點題外話。
> 首先在繼續之前明確我在講述時的身份——ta認爲的“鈴木真依”
> 
> 在我作爲“鈴木真依”時“2022/12/~”,ta曾經因爲自殺干預的原因找到我（CatEars project 的原型），在同時還有另外一位找到我，就是“ARTS”。
> 
> 我在那時和我的朋友一起陪ta聊天，希望ta可以因爲陪伴不要自殺，並在這個過程中ta提出了要和“我”作爲情人關係生活，我就借此給ta提了“不可以自殺”的條件並獲得同意（在這時我同時進行了對於“ARTS”的開導並獲得了她真遺書的加密版本，我使用工具跑了字典，失敗了，後來該副本因爲特殊原因被丟棄），並在這之後進行了大約半年的“文游式”戀愛（即所有信息皆提供虛假的，使用了病弱人設以加强控制之類的...其目標在於保護自己和牽制ta避免自殺行爲），在這之間ta提到了自己曾經進行假紫砂...騙取關注和金幣的行爲並提議在人設崩塌圈不到后使用“轉生林檎”繼續，我接下話題並提供了避免用戶畫像聯想的方法...在後來局勢變化導致我壓力山大（ta會假紫砂並使用紫砂威脅我爆金幣），我將我的人物“鈴木真依”使用充滿破綻的方式寫死了。（那時我就已經在標榜自己為情強，所以是在調查了大量關於心臟病和醫療護理的資料后進行的，因爲一些原因，我希望和我一樣的情強可以很快看出，故使用奇妙深刻而不算離譜的死亡方式——呼吸肌麻痹合并肺炎，因爲臥床和虛弱引起xxx云云）。
> 
> ## 我寫上面的廢話可以在這個主題概括為：
> * 我不是真的想和ta戀愛。
> * 我在和ta戀愛時因爲安全考慮提供虛假身份，這是我的罪過
> * 我在和ta戀愛期間進行了類似於ARG的小範圍表演來鞏固人設以加强控制
> * ta會假紫砂並使用紫砂威脅我爆金幣，并且炫耀自己曾經得手
> * ta會在人設崩塌后嘗試轉生林檎
> * 我在去年的4月份徹底寫死鈴木真依，因爲我無法承受基於生命的綁架
> * 我是騙子
> 
> ## 隨便的題外話：
> * 我在和arts聊天時獲得了好多照片，很好看
> * arts知道我帶著面具，並表示在以後會幫助我圓謊和自炒（和黑塔一起討論我的面具並放出結論），但我需要把檸檬光打趴下（ddos）並將對於檸檬光的黑屁鑄造成NFT
> * arts會在消失后一周定時傳送密碼，届時就可以解密壓縮包獲得真遺書（因爲tg因爲寫死被丟棄，遺書本體存在的電腦因爲警察對我涉及毒品案的調查被沒收）
> * arts...嗯，曾經被認妹妹了嗚嗚嗚

根据相关人打电话核查确实是真走了

**Comment by Yuki-Luofan** [comment]
ok，惋惜
