### ISSUE TITLE
Add @Nekohamoukyuu & @Mikasuda765

### ISSUE THREAD

**Issue by pea-snow** [one-among-us/data#205]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SNOWCH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SNOWCH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

Michicoka   Suda🌙🏳️‍⚧️ | 2007 | 2024.3.8     (約17) | 大量服藥 |   | Mikasuda765
-- | -- | -- | -- | -- | --

</body>

</html>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SNOWCH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SNOWCH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

酷酷猫 | 2000 | 2024.2.28     (23) | 服毒，疑為NaNO₂ |   | Nekohamoukyuu
-- | -- | -- | -- | -- | --

</body>

</html>

以上

**Comment by Twinsherry** [comment]
酷酷猫（游魂）的条目有朋友在负责了，可能还需要一些时间。

Michicoka Soda的情况我们这边不太清楚，包括生前的一些事情和她的朋友。请问能否提供更多信息呢？

**Comment by pea-snow** [comment]
相關資料我可能需要其他人幫忙補全:(

**Comment by Twinsherry** [comment]
> 相關資料我可能需要其他人幫忙補全:(

有相关的联系方式么

**Comment by sauricat** [comment]
经过确认，Mikasuda765 目前情况尚好
游魂的条目仍然在调查和写作中，查看 #250
