### ISSUE TITLE
Add Akechi Satori Plz

### ISSUE THREAD

**Issue by iamapig120** [one-among-us/data#222]
大概已经去世三年多了吧……也许更久……网络留下的痕迹也在越来越少……
还能找到的痕迹
https://ko-fi.com/akechisatori （kofi）
https://twitter.com/fakeChitose （她友人）

**Comment by Twinsherry** [comment]
https://www.zhihu.com/people/akechisatori/following/questions

互联网档案馆备份链接：
https://web.archive.org/web/20211126021414/https://github.com/akechisatori
https://web.archive.org/web/20240327102842/https://github.com/komeiji-satori

感谢您提供的信息，近期秋叶多位成员忙碌，如果您认识友人（看起来是恋人）的话可以事先帮忙询问一下意见……？

**Comment by BBleae** [comment]
放你妈的屁，人家活得好好的

**Comment by iamapig120** [comment]
？？？？？？？
能要个消息来源吗？




手柄
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "one-among-us/data"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, May 20, 2024 08:37 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [one-among-us/data] Add Akechi Satori Plz (Issue #222)





 
放你妈的屁，人家活得好好的

**Comment by LS-KR** [comment]
暂无查证信息可靠源, 本 issue 将保持开启

**Comment by Twinsherry** [comment]
> 暂无查证信息可靠源, 本 issue 将保持开启

经过相关讨论交流，暂时关闭issue。
