### ISSUE TITLE
Meaning of GATH in https://github.com/one-among-us/data/blob/main/people/Aniloviraw/page.en.md ?

### ISSUE THREAD

**Issue by Aquaticat** [one-among-us/data#235]
Need to know if it's a good thing or bad thing to determine how to translate it.
Did  she go off it for a few days or was she  forced to take it for a few days?

**Comment by Twinsherry** [comment]
It was a good thing, I think.
GAHT (Gender-affirming hormone therapy) is another name of HRT.
I'm sorry for that taking so long to handle with this pull request.

**Comment by Aquaticat** [comment]
https://github.com/one-among-us/data/commit/cb784a435c92f4ad6281e7a2e0e6c20e23f139ca
