### ISSUE TITLE
Add 夜猫猫

### ISSUE THREAD

**Issue by canyie** [one-among-us/data#257]
夜猫猫（仿生黑塔会梦见电子星核吗）
https://twitter.com/cmtfdd
https://t.me/cmtfdd
于 2023.11.27 服毒自杀。
本 issue 仅为确认贵项目是否有接收此条目的意愿。我这边可以尝试组织人员编写条目内容。

**Comment by LS-KR** [comment]
夜猫猫生前曾说不要添加她.
