### ISSUE TITLE
Add Arita

### ISSUE THREAD

**Issue by aedna1798** [one-among-us/data#272]
姐姐
反正我觉得是ally就是对吧

**Comment by Twinsherry** [comment]
您好，请问有更多的信息可以提供吗……？

**Comment by aedna1798** [comment]
https://new.qq.com/rain/a/20240405A025LZ00
里面@雨瑶  26岁
这个部分是我写的...大概就进一步完善一下...

**Comment by LS-KR** [comment]
那等我迁移完数据推一下？

对不起我这边是 out of service 的状态

**Comment by LS-KR** [comment]
另外请提供一下生日和祭日（如果可能的话）
以及需要一个常用的唯一 id

**Comment by Twinsherry** [comment]
可能还需要一个常用头像，如果可以的话发送到info@oneamongus.ca 辛苦了

**Comment by aedna1798** [comment]
谢谢大家...那我自己写好了发到邮箱吧

**Comment by Twinsherry** [comment]
您好，目前还在吗，辛苦了……
