### ISSUE TITLE
[Link Expired] - Transgender Factsheet

### ISSUE THREAD

**Issue by yuw446** [one-among-us/data#299]
Link of "[Transgender Factsheet](https://www.unfe.org/wp-content/uploads/2019/03/Transgender_Factsheet_English.pdf)" on the main page leads to a 404. Might want to update link.

**Comment by LS-KR** [comment]
fixed at https://github.com/one-among-us/web/commit/64e6234cf38f4329b4db731ff374860cfb9ad7ed
