### ISSUE TITLE
Add 铃木

### ISSUE THREAD

**Issue by sauricat** [one-among-us/data#42]

**Comment by catears-as** [comment]
这是我们所找到的信息https://twitter.com/CatEars2333/status/1609856988443443201

**Comment by nmsl6653** [comment]
作为她原来的朋友,我会和@catears-as一起提供更多信息...希望请求可以快点被通过...非常感谢哦。

**Comment by sauricat** [comment]
抱歉这里的铃木应该是指另一个人，似乎是我们内部讨论的时候给出的一位 transmasc，没有指清楚导致混淆了。铃木凉宫的 issue #47 被我之前关掉了。现在我们集中在 PR #50 里面讨论的。

**Comment by catears-as** [comment]
> 抱歉这里的铃木应该是指另一个人，似乎是我们内部讨论的时候给出的一位 transmasc，没有指清楚导致混淆了。铃木凉宫的 issue #47 被我之前关掉了。现在我们集中在 PR #50 里面讨论的。

很抱歉給您帶來了不必要的影響，希望您可以原諒我的錯誤...

**Comment by LS-KR** [comment]
……  
是的没错…这个issue又要被拉起了……  
真依也……

**Comment by KagurazakaWind** [comment]
> …… 是的没有错……这个issue又要被拉起来了…… 真的依也……

...呜呜

**Comment by BUAA-Wjay** [comment]
> …… 是的没错…这个issue又要被拉起了…… 真依也……

可能需要更多信息，包括具体离世时间等
