### ISSUE TITLE
Add Chica (凝予)

### ISSUE THREAD

**Issue by sauricat** [one-among-us/data#53]
**Trigger Warning**

For more information, see:
- [Chica's Twitter](https://twitter.com/wangzihao980).
- [Her friend's confirmation and mourning tweets](https://twitter.com/DasUmbralumen/status/1611063012928163841).

There are at least 4 transgender females who have died of suicide since Dec 14, 2022. In such a cold winter, please take care of yourselves before contributing to the community.

**Comment by catears-as** [comment]
> **Trigger Warning**
> 
> 
> 
> For more information, see:
> 
> - [Chica's Twitter](https://twitter.com/wangzihao980).
> 
> - [Her friend's confirmation and mourning tweets](https://twitter.com/DasUmbralumen/status/1611063012928163841).
> 
> 
> 
> There are at least 4 transgender females who have died of suicide since Dec 14, 2022. In such a cold winter, please take care of yourselves before contributing to the community.

我會嘗試修訂新的條目，雖然可能並不完美。同時感謝您善意的提醒喔...

「願逝者安息」

**Comment by lotywe** [comment]
Chica's birthday is May 18
