### ISSUE TITLE
Add tsukiko

### ISSUE THREAD

**Issue by silvicky** [one-among-us/data#59]
https://twitter.com/ttttsuuukikoo_
This is his twitter, I've come to you before, just in case you forget it...

**Comment by sauricat** [comment]
Thank you for your information! We will follow up.

**Comment by Aquaticat** [comment]
Twitter account inaccessible as of 2023 Jan 28th.

**Comment by sauricat** [comment]
It was due to a link formation problem. See [here](https://twitter.com/ttttsuuukikoo_).

**Comment by hykilpikonna** [comment]
> It was due to a link formation problem. See [here](https://twitter.com/ttttsuuukikoo_).

The twitter data is backed up to https://cdn.hydev.org/backup/Twitter/

**Comment by Aquaticat** [comment]
I see.
