### ISSUE TITLE
请求在收录时不要公开自杀方式

### ISSUE THREAD

**Issue by Leravlan** [one-among-us/data#60]
不要公开自杀方式，这可能导致更多人用同样方式自杀。
谢谢了。

**Comment by sauricat** [comment]
感谢您的建议，我们正在对之前的条目进行排查和修改。并且我们正在撰写 [编辑指南](https://github.com/one-among-us/how-we-work) 来应对这个问题。我看到您在我们的评论当中留言了，关于铃木的自杀方式，已经在 [这条 commit](https://github.com/one-among-us/data/commit/caa164d6eabad8b62e23bd94fdd115e792f16755) 中修改好。非常抱歉我们工作的疏忽。

**Comment by catears-as** [comment]
> 感谢您的建议，我们正在对之前的条目进行排查和修改。并且我们正在撰写 [编辑指南](https://github.com/one-among-us/how-we-work) 来应对这个问题。我看到您在我们的评论当中留言了，关于铃木的自杀方式，已经在 [这条 commit](https://github.com/one-among-us/data/commit/caa164d6eabad8b62e23bd94fdd115e792f16755) 中修改好。非常抱歉我们工作的疏忽。

很抱歉使用了錯誤的方式編寫條目...對不起

**Comment by sauricat** [comment]
再次感谢大家的建议，我们在编辑指南中更新了这部分内容。点击 [这里](https://github.com/one-among-us/how-we-work/blob/main/EditingGuide-zh_Hans.md) 查看。
