### ISSUE TITLE
Add noah(noname3031)

### ISSUE THREAD

**Issue by RinLin-NYA** [one-among-us/data#61]
https://twitter.com/noah34981275
As confirmed, she has committed a suicide by using sodium nitrite.
R.I.P.

We need more information to add the entry for her.

**Comment by RinLin-NYA** [comment]
#63 Detected.
After #63 merges, we will close this issue as done.

**Comment by sauricat** [comment]
Close as resolved in #63.

**Comment by RinLin-NYA** [comment]
#63 merged.
