### ISSUE TITLE
Add mone

### ISSUE THREAD

**Issue by RinLin-NYA** [one-among-us/data#62]
https://twitter.com/mone_o_o0
As confirmed, she has committed a suicide by using sodium nitrite.
R.I.P.

We need more information to add the entry for her.

**Comment by RinLin-NYA** [comment]
btw，最近用亚硝酸钠自杀的MtF姐妹们越来越多了......
铃萤对于PRS那份文件流出的可能性表示怀疑

**Comment by sauricat** [comment]
感谢！想问下 PRS 的文件具体是什么？如果不方便在这里说的话，可以邮件到 [info@one-among.us](mailto:info@one-among.us)

**Comment by RinLin-NYA** [comment]
> 



> 感谢！想问下 PRS 的文件具体是什么？如果不方便在这里说的话，可以邮件到 [info@one-among.us](mailto:info@one-among.us)

好
请留意来自 RinLin_NYA@proton.me 的邮件

**Comment by RinLin-NYA** [comment]
> 感谢！想问下 PRS 的文件具体是什么？如果不方便在这里说的话，可以邮件到 [info@one-among.us](mailto:info@one-among.us)

另起一头，接下来我们可以预见的是未来很长一段时间以内一定会有更多MtF姐妹使用亚硝酸钠自杀并成功，因此虽然铃萤也极不愿意提出这一建议，但是咱觉得以后的issues可以合并为一个待办issue以提前做好应对来便于整理
