### ISSUE TITLE
Add Hangmster

### ISSUE THREAD

**Issue by sauricat** [one-among-us/data#85]
https://twitter.com/Hangmster 
Need further investigation.

**Comment by LiAlH4-Tr** [comment]
似乎不符合收录标准

**Comment by BUAA-Wjay** [comment]
> 似乎不符合收录标准

符合友跨人士收入标准，且尽管不适合在纪念文中表明，其似乎具有跨性别倾向

**Comment by LiAlH4-Tr** [comment]
> > 似乎不符合收录标准
> 
> 符合友跨人士收入标准，且尽管不适合在纪念文中表明，其似乎具有跨性别倾向

确实
