### ISSUE TITLE
Add akasha_musha（星云 羽雪🏳️‍🌈🏳️‍⚧️🍥）

### ISSUE THREAD

**Issue by QianYuChan** [one-among-us/data#88]
![20230208_214354](https://user-images.githubusercontent.com/76060243/217546932-58c90347-fb70-4ef4-97c1-5f1c8fd363e9.jpg)
![20230208_214355](https://user-images.githubusercontent.com/76060243/217547002-64a84c0c-9966-4e4e-a97f-98a3ac3ddef4.jpg)

**Comment by MissSuzuki23** [comment]
生日是2009年6月4日

**Comment by sauricat** [comment]
真年轻啊…… 好心疼。

**Comment by BUAA-Wjay** [comment]
我已在编辑她的页面

**Comment by BUAA-Wjay** [comment]
羽雪的页面已经上线，希望大家继续完善

**Comment by sauricat** [comment]
非常感谢…… 暂时关闭这个 Issue 了。
「愿羽雪在天堂成为一个漂漂亮亮的女孩子，永远没有歧视。」这句话看得让我落泪。
