### ISSUE TITLE
Add Akamight

### ISSUE THREAD

**Issue by sauricat** [one-among-us/data#89]
Birth: 2002-01-03 (uncertain)
Death: 2021-02-20

See also the remembrance post in [Limelight](https://limelight.moe/t/topic/5721).
See also the profile [image](https://user-images.githubusercontent.com/3533655/218298494-776864fd-11bb-42ad-a8fb-544f2a8b83db.png).
We need more about her stories.

Issue raised by: Aigül Feng.

**Comment by Lhcfl** [comment]
我是limelight同期活跃用户，Akamight（小圆）和Suzukimarute（鈴木丸輝）生前的朋友，应该总归也算比较熟悉的人。我个人的想法是不太希望上述二位被放在「那些秋叶」，希望他们能更加安静的离开。

不过，我不反对有同样作为他们的友人，把他们加上「那些秋叶」以纪念的权力。仅仅阐述一下个人意见。

**Comment by sauricat** [comment]
如果是目前在世的人，不愿意去世之后被那些秋叶收录，可以通过邮件或者其他联系方式告诉我们自己身后的意愿（当然，这两位都是在网站运营并且为人熟知之前去世的，就没有办法问她们自己的意愿，非常遗憾）。如果是亲属或者非常亲近的朋友在逝者去世之后提出意见，我们一般也会遵循。小圆和铃木的 Issue，我们也是因为接到生前朋友的要求，才开启的。之后如果有写出贡献条目 的话，也希望你能再提出一些自己的意见，包括评估写好的稿子是否应该放上去。

谢谢你对那些秋叶的关注和支持！

**Comment by sauricat** [comment]
介于 limelight 上的讨论，以及较多生前亲友不愿意她被收录，暂时关闭这个 Issue。
