### ISSUE TITLE
Add 阿鸢

### ISSUE THREAD

**Issue by LS-KR** [one-among-us/data#93]
https://twitter.com/qianyuanakg/status/1627338646260183045  
https://twitter.com/YaoMengJiang/status/1627550061508063232

**Comment by sauricat** [comment]
Thank you for your information.

**Comment by Twinsherry** [comment]
阿鸢的相关事情已经大致了解，目前联系到一位较近的朋友，但朋友由于家庭变故原因近期一段时间可能暂时无法详细回复。

**Comment by Twinsherry** [comment]
已经从友人处获得相关的消息，移除标签。
