### ISSUE TITLE
Add Mio

### ISSUE THREAD

**Issue by biliacat** [one-among-us/data#98]
<img width="439" alt="Mio1" src="https://user-images.githubusercontent.com/67852913/221366209-c7771afc-8cb4-4ace-84fe-951a8f94deaa.png">

<img width="440" alt="Mio2" src="https://user-images.githubusercontent.com/67852913/221366247-24ee162f-ae59-427b-98e7-08b4ae8c03e2.png">

咱是Mio的好朋友，如果有什么需要补充的请联系我。

**Comment by sauricat** [comment]
收到，谢谢你。
补一些链接：
https://twitter.com/Harunome_Hanbai/status/1629380645976965120
https://twitter.com/biliacat/status/1629370869482160129
https://twitter.com/biliacat/status/1629313299694366723

**Comment by biliacat** [comment]
若要添加Mio生前的照片，请避免把咱的样子放上去。
咱的衣服是白色的，Mio的衣服是粉色的。
谢谢。

**Comment by BeiyanYunyi** [comment]
我来写吧。我是她小学最要好的同班同学，后来基友变姬友，我对她这个阶段比较了解，但后来的事还需要各位额外补充一下。

**Comment by Dawn-Xu-helloworld** [comment]
呜呜呜呜，我是群友，她真的是一个超级好的大姐姐，心疼

**Comment by BeiyanYunyi** [comment]
> 若要添加Mio生前的照片，请避免把咱的样子放上去。

是需要截掉还是打码？

**Comment by BeiyanYunyi** [comment]
#99 我写了一部分，剩下的拜托各位了。

**Comment by BeiyanYunyi** [comment]
截掉了，麻烦提供一下出生日期……我只记得她比我小一岁多

**Comment by biliacat** [comment]
> 

2001.12.26

**Comment by biliacat** [comment]
![IMG_7919](https://user-images.githubusercontent.com/67852913/221411619-36a6f7c7-72f9-4550-880e-33a8056c6fcc.jpeg)

一些补充

**Comment by BeiyanYunyi** [comment]
好的。

**Comment by biliacat** [comment]
![IMG_6812](https://user-images.githubusercontent.com/67852913/221412483-837b1a7f-f5aa-487b-9821-9040e9df3ea1.jpeg)
![IMG_5831](https://user-images.githubusercontent.com/67852913/221412558-7aed4cf5-7dd1-47b9-9fc1-e0b0a1ba8e99.jpeg)

p1是她在机场送我上大学离去时的背影
p2是我和她出去玩时两个人的见证
我和她总共在一个多月的时间里见了6次，真的很痛心…
麻烦也加上去吧

**Comment by BeiyanYunyi** [comment]
已加。

**Comment by BeiyanYunyi** [comment]
……我可能需要明确一下在页面上对你的称呼，用“伴侣”“女友”是否合适？

**Comment by BeiyanYunyi** [comment]
具体行文请参照：https://github.com/one-among-us/data/pull/99/files 中的 people/Mio/page.md 页面

**Comment by biliacat** [comment]
> ……我可能需要明确一下在页面上对你的称呼，因为她没有向我明确过这段关系的性质。我在页面上用“伴侣”“女友”来称呼是否合适？

请采用“mtf闺蜜”的称呼。

**Comment by BeiyanYunyi** [comment]
> 请采用“mtf闺蜜”的称呼。

好的。

**Comment by BeiyanYunyi** [comment]
这个 issue 可以 close 了。@sauricat @Aquaticat

**Comment by Aquaticat** [comment]
> 这个 issue 可以 close 了。@sauricat @Aquaticat

感谢提醒。已关闭。
